### ISSUE TITLE
Tag old version

### ISSUE THREAD

**Issue by vlakarados** [amphp/injector#13]
For BC and as @kelunik is bringing a totally new approach to be used in this library, create a tag for the latest version before these changes, I guess, up to this commit: https://github.com/amphp/injector/commit/378753e1a8afc83791d7a5a182b213bb72640bfd

This is especially important for those who wish to keep using the PHP 8 version of auryn as well as those who see that it's deprecated and forwarded to this library.

**Comment by kelunik** [comment]
Please keep using `rdlowrey/auryn` for the old version. It won't be tagged in this repository.
