### ISSUE TITLE
PHP 7 fork

### ISSUE THREAD

**Issue by szepeviktor** [amphp/injector#4]
# Welcome to my fork for people running PHP 7.4!

It will be fun. :)

https://github.com/szepeviktor/injector-php-7

**Comment by kelunik** [comment]
`rdlowrey/auryn` should work just fine for PHP 7.4. But I'm also not entirely sure whether 8.0 will really be the minimum requirement.

**Comment by szepeviktor** [comment]
🤯 Oh no!

This is my contribution: https://github.com/szepeviktor/injector-php-7/commit/dff06c99c83ac412d6be4987d4e198e708df3ff4

**Comment by szepeviktor** [comment]
> 1) Amp\Injector\InjectorTest::testMakeInstanceThrowsExceptionOnClassLoadFailure
Failed asserting that exception message 
```
'Could not make ClassThatDoesntExist: Class ClassThatDoesntExist does not exist' contains 
'Could not make ClassThatDoesntExist: Class "ClassThatDoesntExist" does not exist'.
```

Do these quotes come from PHP 8?

**Comment by kelunik** [comment]
I haven't looked where these come from, yet.

**Comment by szepeviktor** [comment]
On PHP 8 quoted messages pass, on PHP 7.4 tests fail.

**Comment by kelunik** [comment]
I guess it's new then.

**Comment by szepeviktor** [comment]
Published the PHP 7 compatible package.
https://packagist.org/packages/szepeviktor/injector-php-7
I encourage you to remove those `mixed` types and be PHP 7 compatible.
